In [ ]:
import pandas as pd

In [ ]:
# Create the kaggle directory
!mkdir ~/.kaggle

mkdir: cannot create directory ‘/root/.kaggle’: File exists

In [ ]:
# Read the uploaded kaggle.json file
!cp /content/drive/MyDrive/kaggle.json ~/.kaggle/

cp: cannot stat '/content/drive/MyDrive/kaggle.json': No such file or directory

In [ ]:
# Download dataset
!kaggle datasets download joebeachcapital/airbnb

Dataset URL: https://www.kaggle.com/datasets/joebeachcapital/airbnb
License(s): CC0-1.0
Downloading airbnb.zip to /content
 99% 1.00G/1.01G [00:09<00:00, 131MB/s]
100% 1.01G/1.01G [00:09<00:00, 110MB/s]

In [ ]:
# Unzip folder in Colab content folder
!unzip /content/airbnb.zip

Archive:  /content/airbnb.zip
  inflating: airbnb-listings.csv
  inflating: airbnb-listings.geojson

In [ ]:
# Read the csv files into pandas df
airbnb = pd.read_csv('airbnb-listings.csv', delimiter=';', quotechar='"')

<ipython-input-11-8026b52ac2b9>:2: DtypeWarning: Columns (0,2,66) have mixed types. Specify dtype option on import or set low_memory=False.
  airbnb = pd.read_csv('airbnb-listings.csv', delimiter=';', quotechar='"')

In [ ]:
airbnb = airbnb[['ID', 'Neighbourhood', 'City', 'State', 'Country', 'Latitude', 'Longitude', 'Property Type', 'Accommodates', 'Bathrooms',
                 'Bedrooms', 'Beds', 'Price', 'Guests Included', 'Extra People', 'Minimum Nights', 'Maximum Nights', 'Number of Reviews',
                 'Review Scores Rating']]

In [ ]:
airbnb = airbnb.dropna()

In [ ]:
airbnb

,ID,Neighbourhood,City,State,Country,Latitude,Longitude,Property Type,Accommodates,Bathrooms,Bedrooms,Beds,Square Feet,Price,Guests Included,Extra People,Minimum Nights,Maximum Nights,Number of Reviews,Review Scores Rating
0,4008728,Oud-West,Amsterdam,North Holland,Netherlands,52.365237,4.878250,Apartment,6.0,1.0,3.0,3.0,NaN,600.0,4.0,50.0,2.0,1125.0,31.0,89.0
1,7778612,Oud-West,Amsterdam,Noord-Holland,Netherlands,52.367309,4.873841,Apartment,4.0,1.0,2.0,2.0,NaN,175.0,2.0,30.0,2.0,1125.0,15.0,99.0
2,8264596,Oud-West,Amsterdam,Noord-Holland,Netherlands,52.361944,4.866687,Apartment,4.0,1.0,2.0,2.0,NaN,125.0,1.0,0.0,4.0,1125.0,1.0,100.0
3,2180729,Oud-West,Amsterdam,Noord-Holland,Netherlands,52.370146,4.866282,Apartment,4.0,1.0,2.0,4.0,NaN,130.0,2.0,25.0,3.0,30.0,22.0,97.0
4,14463171,NaN,Amsterdam,Noord-Holland,Netherlands,52.368818,4.871249,Apartment,2.0,1.0,0.0,1.0,NaN,80.0,1.0,0.0,2.0,1125.0,16.0,78.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
494949,12856943,Footscray,Footscray,VIC,Australia,-37.796844,144.882124,House,2.0,1.5,1.0,1.0,NaN,30.0,1.0,12.0,1.0,1125.0,4.0,60.0
494950,4567157,Yarraville/Seddon,Yarraville,VIC,Australia,-37.816746,144.880878,House,2.0,1.0,1.0,1.0,NaN,42.0,1.0,10.0,7.0,1125.0,9.0,93.0
494951,16681466,NaN,West Footscray,VIC,Australia,-37.804905,144.868357,House,1.0,1.0,1.0,1.0,NaN,33.0,1.0,0.0,3.0,1125.0,3.0,100.0
494952,17179364,NaN,Footscray,VIC,Australia,-37.792251,144.894132,Apartment,4.0,1.0,1.0,2.0,NaN,62.0,1.0,0.0,5.0,30.0,0.0,NaN
494953,10735664,Yarraville/Seddon,Kingsville,VIC,Australia,-37.811684,144.880698,House,2.0,1.0,1.0,1.0,NaN,47.0,1.0,15.0,2.0,1125.0,0.0,NaN

In [ ]:
from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive

In [ ]:
airbnb.to_csv('/content/drive/MyDrive/airbnb_cleaned.csv')